//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoJune
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.IstoriaPrioritetnostiPostavki = new HashSet<IstoriaPrioritetnostiPostavki>();
            this.IstoriaRealizashiiProductii = new HashSet<IstoriaRealizashiiProductii>();
            this.ToskiProdaji = new HashSet<ToskiProdaji>();
            this.Zaiavka = new HashSet<Zaiavka>();
        }
    
        public int AgentId { get; set; }
        public string ImaAgenta { get; set; }
        public string ImaCompanii { get; set; }
        public string UridisheskiiAdres { get; set; }
        public string Inn { get; set; }
        public string Kpp { get; set; }
        public string FamiliaDirectora { get; set; }
        public string ImaDirectora { get; set; }
        public string OtchestvoDirectora { get; set; }
        public string Telefon { get; set; }
        public string Pothta { get; set; }
        public string Logotip { get; set; }
        public short PrioritetnostPostavkah { get; set; }
        public int TipAgentaId { get; set; }

    

        public virtual TipAgenta TipAgenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IstoriaPrioritetnostiPostavki> IstoriaPrioritetnostiPostavki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IstoriaRealizashiiProductii> IstoriaRealizashiiProductii { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToskiProdaji> ToskiProdaji { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zaiavka> Zaiavka { get; set; }

       
    }
}
