//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoJune
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriMestopolodjenieSotrydnikov
    {
        public long HistoriMestopolodjenieSotrydnikovId { get; set; }
        public System.DateTime DateTimePosehenia { get; set; }
        public int SotrydnikId { get; set; }
        public byte MestaKompaniiId { get; set; }
    
        public virtual MestaKompanii MestaKompanii { get; set; }
        public virtual Sotrydnik Sotrydnik { get; set; }
    }
}
