//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoJune
{
    using System;
    using System.Collections.Generic;
    
    public partial class IstoriaPrioritetnostiPostavki
    {
        public int IstoriaPrioritetnostiPostavkiId { get; set; }
        public int AgentId { get; set; }
        public short Proiritetnost { get; set; }
    
        public virtual Agent Agent { get; set; }
    }
}
