//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoJune
{
    using System;
    using System.Collections.Generic;
    
    public partial class IstoriaIzmeneniMinStoimostDlaAgent
    {
        public int IstoriaIzmeneniMinStoimostDlaAgentId { get; set; }
        public int ZaiavkaId { get; set; }
        public System.DateTime DateZaiavki { get; set; }
    
        public virtual Zaiavka Zaiavka { get; set; }
    }
}
