//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoJune
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.HistoriaIzmeneniiKolisestvaMterialov = new HashSet<HistoriaIzmeneniiKolisestvaMterialov>();
            this.IstoriaPostypleniaMaterialov = new HashSet<IstoriaPostypleniaMaterialov>();
            this.Postavshik = new HashSet<Postavshik>();
            this.SpisokMaterialDlaProizvodstvaProdyctii = new HashSet<SpisokMaterialDlaProizvodstvaProdyctii>();
        }
    
        public int MaterialId { get; set; }
        public string Naimenovanie { get; set; }
        public int TipMaterialId { get; set; }
        public short KolihestwoVYpakovke { get; set; }
        public string EdinishaIzmerenia { get; set; }
        public short KolichestvoNaSklade { get; set; }
        public string Opisanie { get; set; }
        public string Izobrajenie { get; set; }
        public decimal Stoimost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoriaIzmeneniiKolisestvaMterialov> HistoriaIzmeneniiKolisestvaMterialov { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IstoriaPostypleniaMaterialov> IstoriaPostypleniaMaterialov { get; set; }
        public virtual TipMaterial TipMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Postavshik> Postavshik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpisokMaterialDlaProizvodstvaProdyctii> SpisokMaterialDlaProizvodstvaProdyctii { get; set; }
    }
}
