//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoJune
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProizvodstvoEntities : DbContext
    {
        public ProizvodstvoEntities()
            : base("name=ProizvodstvoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<HistoriaIzmeneniiKolisestvaMterialov> HistoriaIzmeneniiKolisestvaMterialov { get; set; }
        public virtual DbSet<HistoriMestopolodjenieSotrydnikov> HistoriMestopolodjenieSotrydnikov { get; set; }
        public virtual DbSet<IstoriaIzmeneniMinStoimostDlaAgent> IstoriaIzmeneniMinStoimostDlaAgent { get; set; }
        public virtual DbSet<IstoriaPostypleniaMaterialov> IstoriaPostypleniaMaterialov { get; set; }
        public virtual DbSet<IstoriaPrioritetnostiPostavki> IstoriaPrioritetnostiPostavki { get; set; }
        public virtual DbSet<IstoriaRealizashiiProductii> IstoriaRealizashiiProductii { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<MestaKompanii> MestaKompanii { get; set; }
        public virtual DbSet<NomeraStandatrta> NomeraStandatrta { get; set; }
        public virtual DbSet<Postavshik> Postavshik { get; set; }
        public virtual DbSet<Productshia> Productshia { get; set; }
        public virtual DbSet<Proizvodstvo> Proizvodstvo { get; set; }
        public virtual DbSet<Sotrydnik> Sotrydnik { get; set; }
        public virtual DbSet<Speshialnost> Speshialnost { get; set; }
        public virtual DbSet<SpisokMaterialDlaProizvodstvaProdyctii> SpisokMaterialDlaProizvodstvaProdyctii { get; set; }
        public virtual DbSet<TipAgenta> TipAgenta { get; set; }
        public virtual DbSet<TipMaterial> TipMaterial { get; set; }
        public virtual DbSet<TipPostavshika> TipPostavshika { get; set; }
        public virtual DbSet<TipProdycta> TipProdycta { get; set; }
        public virtual DbSet<ToskiProdaji> ToskiProdaji { get; set; }
        public virtual DbSet<Zaiavka> Zaiavka { get; set; }
    }
}
