//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoJune
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productshia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productshia()
        {
            this.IstoriaRealizashiiProductii = new HashSet<IstoriaRealizashiiProductii>();
            this.Proizvodstvo = new HashSet<Proizvodstvo>();
            this.SpisokMaterialDlaProizvodstvaProdyctii = new HashSet<SpisokMaterialDlaProizvodstvaProdyctii>();
            this.Zaiavka = new HashSet<Zaiavka>();
        }
    
        public int ProductshiaId { get; set; }
        public string Artikul { get; set; }
        public string Naimenovanie { get; set; }
        public string Opisanie { get; set; }
        public string Izobradjenie { get; set; }
        public decimal MinStoimostProductaDlaAgenta { get; set; }
        public short DlinaYpakovki { get; set; }
        public short ShirinaYpakovki { get; set; }
        public short VisotaYpakovki { get; set; }
        public short VesBezYpakovki { get; set; }
        public short VesSYpakovki { get; set; }
        public string SertifikatCathestva { get; set; }
        public short NomeraStandatrtaId { get; set; }
        public short TipProdyctaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IstoriaRealizashiiProductii> IstoriaRealizashiiProductii { get; set; }
        public virtual NomeraStandatrta NomeraStandatrta { get; set; }
        public virtual TipProdycta TipProdycta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proizvodstvo> Proizvodstvo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpisokMaterialDlaProizvodstvaProdyctii> SpisokMaterialDlaProizvodstvaProdyctii { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zaiavka> Zaiavka { get; set; }
    }
}
