//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoJune
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrydnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrydnik()
        {
            this.HistoriMestopolodjenieSotrydnikov = new HashSet<HistoriMestopolodjenieSotrydnikov>();
            this.Proizvodstvo = new HashSet<Proizvodstvo>();
        }
    
        public int SotrydnikId { get; set; }
        public string Foto { get; set; }
        public string Familia { get; set; }
        public string Ima { get; set; }
        public string Othestvo { get; set; }
        public System.DateTime DateRozdenia { get; set; }
        public string SeriaPasporta { get; set; }
        public string NomerPasporta { get; set; }
        public string MestoProzivania { get; set; }
        public string MestoRozdenia { get; set; }
        public string KemVidanPasport { get; set; }
        public System.DateTime DateVidachiPasporta { get; set; }
        public string KodPodrazdeleniaPasporta { get; set; }
        public string ShetPolushtela { get; set; }
        public string BankPolushatela { get; set; }
        public string InnBanka { get; set; }
        public string BikBanka { get; set; }
        public string KorrespondentskiiShet { get; set; }
        public bool StatusDjenat { get; set; }
        public byte KolishetvoDetei { get; set; }
        public string ProblemiSoZdoroviem { get; set; }
        public string GraphikRaboty { get; set; }
        public short SpeshialnostId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoriMestopolodjenieSotrydnikov> HistoriMestopolodjenieSotrydnikov { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proizvodstvo> Proizvodstvo { get; set; }
        public virtual Speshialnost Speshialnost { get; set; }
    }
}
